resource_types:
  - name: gcs
    type: docker-image
    source:
      repository: frodenas/gcs-resource

resources:
  ## Image Resources
  - name: gpdb6-centos6-build
    type: docker-image
    source:
      repository: pivotaldata/gpdb6-centos6-build
      tag: 'latest'

  - name: gpdb6-centos7-build
    type: docker-image
    source:
      repository: pivotaldata/gpdb6-centos7-build
      tag: 'latest'

  - name: gpdb6-ubuntu18.04-build
    type: docker-image
    source:
      repository: pivotaldata/gpdb6-ubuntu18.04-build
      tag: 'latest'

  - name: gpdb_src
    type: git
    source:
      branch: ((gpdb-git-branch))
      uri: ((gpdb-git-remote))
      tag_filter: ((gpdb-git-tag-filter))

  - name: greenplum-database-release_src
    type: git
    source:
      branch: ((greenplum-database-release-git-branch))
      uri: ((greenplum-database-release-git-remote))

  - name: gpdb_release
    type: github-release
    source:
      owner: ((gpdb-release-owner))
      repository: ((gpdb-release-repository))
      access_token: ((gpdb-release-access-token))

  - name: license_file
    type: gcs
    source:
      bucket: ((gcs-bucket-for-oss))
      json_key: ((concourse-gcs-resources-service-account-key))
      regexp: osl/released/gpdb6/open_source_license_greenplum-database-(.*)-[a-z0-9]+-[0-9]+.txt

  ## gp internal artifacts
  - name: python-centos6
    type: gcs
    source:
      bucket: ((pivotal-gp-internal-artifacts-gcs-bucket))
      json_key: ((gcs-key))
      versioned_file: centos6/python-2.7.12.tar.gz

  - name: python-centos7
    type: gcs
    source:
      bucket: ((pivotal-gp-internal-artifacts-gcs-bucket))
      json_key: ((gcs-key))
      versioned_file: centos7/python-2.7.12.tar.gz

  - name: python-ubuntu18.04
    type: gcs
    source:
      bucket: gp-internal-artifacts
      json_key: ((gcs-key))
      versioned_file: ubuntu18.04/python-2.7.12.tar.gz

  ## RHEL6 Resources
  - name: bin_gpdb_centos6
    type: gcs
    source:
      json_key: {{concourse-gcs-resources-service-account-key}}
      bucket: {{gcs-bucket-intermediates-for-oss}}
      versioned_file: ((pipeline-name))/bin_gpdb_centos6/bin_gpdb.tar.gz

  - name: bin_gpdb_centos6_release
    type: gcs
    source:
      bucket: ((gcs-bucket-for-oss))
      json_key: ((concourse-gcs-resources-service-account-key))
      regexp: greenplum-oss-server/released/gpdb6/server-(.*)-rhel6_x86_64.tar.gz

  ## RHEL7 Resources
  - name: bin_gpdb_centos7
    type: gcs
    source:
      json_key: {{concourse-gcs-resources-service-account-key}}
      bucket: {{gcs-bucket-intermediates-for-oss}}
      versioned_file: ((pipeline-name))/bin_gpdb_centos7/bin_gpdb.tar.gz

  - name: bin_gpdb_centos7_release
    type: gcs
    source:
      bucket: ((gcs-bucket-for-oss))
      json_key: ((concourse-gcs-resources-service-account-key))
      regexp: greenplum-oss-server/released/gpdb6/server-(.*)-rhel7_x86_64.tar.gz

  ## Ubuntu18.04 Resources
  - name: bin_gpdb_ubuntu18.04
    type: gcs
    source:
      json_key: {{concourse-gcs-resources-service-account-key}}
      bucket: {{gcs-bucket-intermediates-for-oss}}
      versioned_file: ((pipeline-name))/bin_gpdb_ubuntu18.04/bin_gpdb.tar.gz

  - name: bin_gpdb_ubuntu18.04_release
    type: gcs
    source:
      bucket: ((gcs-bucket-for-oss))
      json_key: ((concourse-gcs-resources-service-account-key))
      regexp: greenplum-oss-server/released/gpdb6/server-(.*)-ubuntu18.04_x86_64.tar.gz

  - name: gpdb_debian_package
    type: gcs
    source:
      bucket: ((gcs-bucket-for-oss))
      json_key: ((concourse-gcs-resources-service-account-key))
      regexp: greenplum-oss-server/released/gpdb6/greenplum-db-(.*)-ubuntu18.04-amd64.deb

jobs:
  - name: compile_gpdb_centos6
    plan:
      - aggregate:
          - get: gpdb_src
            trigger: true
          - get: greenplum-database-release_src
          - get: gpdb6-centos6-build
          - get: python-tarball
            resource: python-centos6
      - task: compile_gpdb
        file: greenplum-database-release_src/concourse/tasks/compile_gpdb_oss.yml
        image: gpdb6-centos6-build
      - put: bin_gpdb_centos6
        params:
          file: gpdb_artifacts/bin_gpdb.tar.gz

  - name: compile_gpdb_centos7
    plan:
      - aggregate:
          - get: gpdb_src
            trigger: true
          - get: greenplum-database-release_src
          - get: gpdb6-centos7-build
          - get: python-tarball
            resource: python-centos7
      - task: compile_gpdb
        image: gpdb6-centos7-build
        file: greenplum-database-release_src/concourse/tasks/compile_gpdb_oss.yml
      - put: bin_gpdb_centos7
        params:
          file: gpdb_artifacts/bin_gpdb.tar.gz

  - name: compile_gpdb_ubuntu18.04
    plan:
      - aggregate:
          - get: gpdb_src
            trigger: true
          - get: greenplum-database-release_src
          - get: gpdb6-ubuntu18.04-build
          - get: python-tarball
            resource: python-ubuntu18.04
      - task: compile_gpdb
        image: gpdb6-ubuntu18.04-build
        file: greenplum-database-release_src/concourse/tasks/compile_gpdb_oss.yml
      - put:  bin_gpdb_ubuntu18.04
        params:
          file: gpdb_artifacts/bin_gpdb.tar.gz

  - name: create_gpdb_tarball_centos6
    plan:
      - aggregate:
          - get: gpdb_src
            trigger: true
            passed: [compile_gpdb_centos6]
          - get: bin_gpdb_centos6
            passed: [compile_gpdb_centos6]
          - get: gpdb6-centos6-build
      # Even though we don't ship the QA utils, we still need to strip out non-shipping files
      - task: separate_qautils_files_for_rc_centos6
        file: gpdb_src/concourse/tasks/separate_qautils_files_for_rc.yml
        image: gpdb6-centos6-build
        input_mapping:
          bin_gpdb: bin_gpdb_centos6
        output_mapping:
          rc_bin_gpdb: rc_bin_gpdb_rhel6
        params:
          QAUTILS_TARBALL: "rc_bin_gpdb/QAUtils-rhel6-x86_64.tar.gz"
      - put: bin_gpdb_centos6
        params:
          file: rc_bin_gpdb_rhel6/bin_gpdb.tar.gz

  - name: create_gpdb_tarball_centos7
    plan:
      - aggregate:
          - get: gpdb_src
            trigger: true
            passed: [compile_gpdb_centos7]
          - get: bin_gpdb_centos7
            passed: [compile_gpdb_centos7]
          - get: gpdb6-centos7-build
      # Even though we don't ship the QA utils, we still need to strip out non-shipping files
      - task: separate_qautils_files_for_rc_centos7
        file: gpdb_src/concourse/tasks/separate_qautils_files_for_rc.yml
        image: gpdb6-centos7-build
        input_mapping:
          bin_gpdb: bin_gpdb_centos7
        output_mapping:
          rc_bin_gpdb: rc_bin_gpdb_rhel7
        params:
          QAUTILS_TARBALL: "rc_bin_gpdb/QAUtils-rhel7-x86_64.tar.gz"
      - put: bin_gpdb_centos7
        params:
          file: rc_bin_gpdb_rhel7/bin_gpdb.tar.gz

  - name: ubuntu18.04 packaging
    plan:
      - aggregate:
          - get: gpdb_src
            trigger: true
            passed: [compile_gpdb_ubuntu18.04]
          - get: greenplum-database-release_src
            passed: [compile_gpdb_ubuntu18.04]
          - get: bin_gpdb_ubuntu18.04
            passed: [compile_gpdb_ubuntu18.04]
          - get: gpdb6-ubuntu18.04-build
      # Even though we don't ship the QA utils, we still need to strip out non-shipping files
      - task: separate_qautils_files_for_rc_ubuntu18.04
        file: gpdb_src/concourse/tasks/separate_qautils_files_for_rc.yml
        image: gpdb6-ubuntu18.04-build
        input_mapping:
          bin_gpdb: bin_gpdb_ubuntu18.04
        output_mapping:
          rc_bin_gpdb: rc_bin_gpdb_ubuntu18.04
        params:
          QAUTILS_TARBALL: "rc_bin_gpdb/QAUtils-ubuntu18.04-amd64.tar.gz"
      - task: create_gpdb_debian_package
        file: greenplum-database-release_src/concourse/tasks/build_gpdb_debian.yml
        image: gpdb6-ubuntu18.04-build
        input_mapping:
          bin_gpdb: rc_bin_gpdb_ubuntu18.04
        params:
          PLATFORM: "ubuntu18.04"
      - aggregate:
        - put: bin_gpdb_ubuntu18.04
          params:
            file: rc_bin_gpdb_ubuntu18.04/bin_gpdb.tar.gz
        - put: gpdb_debian_package
          params:
            file: gpdb_debian_installer/*.deb

  - name: release
    plan:
      - aggregate:
          - get: gpdb_src
            passed:
              - create_gpdb_tarball_centos6
              - create_gpdb_tarball_centos7
              - ubuntu18.04 packaging
          - get: bin_gpdb_centos6
            passed: [create_gpdb_tarball_centos6]
            trigger: true
          - get: bin_gpdb_centos7
            passed: [create_gpdb_tarball_centos7]
            trigger: true
          - get: bin_gpdb_ubuntu18.04
            passed: [ubuntu18.04 packaging]
            trigger: true
          - get: gpdb_debian_package
            passed: [ubuntu18.04 packaging]
          - get: gpdb6-centos6-build
      - task: rename_gpdb_tarball
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: pivotaldata/gpdb6-centos6-build
          inputs:
            - name: gpdb_src
            - name: bin_gpdb_centos6
            - name: bin_gpdb_centos7
            - name: bin_gpdb_ubuntu18.04
          outputs:
            - name: releases
          run:
            path: bash
            args:
              - -ec
              - |
                gpdb_semver=$(gpdb_src/getversion | cut -d' ' -f1)
                cp -v bin_gpdb_centos6/bin_gpdb.tar.gz releases/server-${gpdb_semver}-rhel6_x86_64.tar.gz
                cp -v bin_gpdb_centos7/bin_gpdb.tar.gz releases/server-${gpdb_semver}-rhel7_x86_64.tar.gz
                cp -v bin_gpdb_ubuntu18.04/bin_gpdb.tar.gz releases/server-${gpdb_semver}-ubuntu18.04_x86_64.tar.gz
      - task: verify_gpdb_versions
        file: gpdb_src/concourse/tasks/verify_gpdb_versions.yml
      - aggregate:
          - put: bin_gpdb_centos6_release
            params:
              file: "releases/server-*rhel6*.tar.gz"
          - put: bin_gpdb_centos7_release
            params:
              file: "releases/server-*rhel7*.tar.gz"
          - put: bin_gpdb_ubuntu18.04_release
            params:
              file: "releases/server-*ubuntu18.04*.tar.gz"

  - name: publish_gpdb_github_release
    plan:
      - aggregate:
          - get: gpdb_src
            trigger: true
            passed: [release]
          - get: license_file
          - get: gpdb_debian_package
            passed: [release]
          - get: greenplum-database-release_src
      - task: gpdb_github_release
        file: greenplum-database-release_src/concourse/tasks/gpdb_github_release.yml
      - put: gpdb_release
        params:
          name: release_artifacts/name
          tag: release_artifacts/tag
          body: release_artifacts/body
          commitish: release_artifacts/commitish
          globs:
            - release_artifacts/*.tar.gz
            - release_artifacts/*.zip
            - license_file/*.txt
            - gpdb_debian_package/*.deb