---
## ======================================================================
##                                           _
##  _ __ ___  ___  ___  _   _ _ __ ___ ___  | |_ _   _ _ __   ___  ___
## | '__/ _ \/ __|/ _ \| | | | '__/ __/ _ \ | __| | | | '_ \ / _ \/ __|
## | | |  __/\__ \ (_) | |_| | | | (_|  __/ | |_| |_| | |_) |  __/\__ \
## |_|  \___||___/\___/ \__,_|_|  \___\___|  \__|\__, | .__/ \___||___/
##                                               |___/|_|
## ======================================================================
resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/tanzunet-resource
    tag: latest-final

- name: gcs
  type: docker-image
  source:
    repository: frodenas/gcs-resource

## ======================================================================
##  _ __ ___  ___  ___  _   _ _ __ ___ ___  ___
## | '__/ _ \/ __|/ _ \| | | | '__/ __/ _ \/ __|
## | | |  __/\__ \ (_) | |_| | | | (_|  __/\__ \
## |_|  \___||___/\___/ \__,_|_|  \___\___||___/
## ======================================================================
resources:
- name: greenplum-database-release
  type: git
  source:
    branch: ((greenplum-database-release-git-branch))
    uri: ((greenplum-database-release-git-remote))

- name: bin_gpdb_centos6
  type: gcs
  source:
    bucket: pivotal-gpdb-concourse-resources-prod
    json_key: ((concourse-gcs-resources-service-account-key))
    regexp: server/published/gpdb6/server-rc-(.*)-rhel6_x86_64.tar.gz

- name: bin_gpdb_centos7
  type: gcs
  source:
    bucket: pivotal-gpdb-concourse-resources-prod
    json_key: ((concourse-gcs-resources-service-account-key))
    regexp: server/published/gpdb6/server-rc-(.*)-rhel7_x86_64.tar.gz

- name: bin_gpdb_ubuntu18.04
  type: gcs
  source:
    bucket: pivotal-gpdb-concourse-resources-prod
    json_key: ((concourse-gcs-resources-service-account-key))
    regexp: server/published/gpdb6/server-rc-(.*)-ubuntu18.04_x86_64.tar.gz

- name: gpdb6-centos6-build
  type: docker-image
  source:
    repository: pivotaldata/gpdb6-centos6-build
    tag: latest

- name: gpdb6-centos7-build
  type: docker-image
  source:
    repository: pivotaldata/gpdb6-centos7-build
    tag: latest

- name: gpdb6-ubuntu18.04-build
  type: docker-image
  source:
    repository: pivotaldata/gpdb6-ubuntu18.04-build
    tag: latest

- name: gpdb-osl
  type: gcs
  source:
    bucket: pivotal-gpdb-concourse-resources-prod
    json_key: ((concourse-gcs-resources-service-account-key))
    regexp: osl/released/gpdb6/open_source_license_VMware_Tanzu_Greenplum_Database_(((gpdb-osl-version-regex)))_GA.txt

- name: rpm_gpdb_centos6
  type: gcs
  source:
    bucket: ((gcs-bucket-intermediates))
    json_key: ((concourse-gcs-resources-service-account-key))
    versioned_file: ((pipeline-name))/rpm_gpdb_centos6/greenplum-db-rhel6-x86_64.rpm

- name: rpm_gpdb_centos7
  type: gcs
  source:
    bucket: ((gcs-bucket-intermediates))
    json_key: ((concourse-gcs-resources-service-account-key))
    versioned_file: ((pipeline-name))/rpm_gpdb_centos7/greenplum-db-rhel7-x86_64.rpm

- name: deb_gpdb_ubuntu18.04
  type: gcs
  source:
    bucket: ((gcs-bucket-intermediates))
    json_key: ((concourse-gcs-resources-service-account-key))
    versioned_file: ((pipeline-name))/deb_gpdb_ubuntu18.04/greenplum-db-ubuntu18.04-amd64.deb

- name: previous-6-release
  type: tanzunet
  source:
    api_token: ((public-tanzunet-refresh-token))
    endpoint: ((tanzunet-endpoint))
    product_slug: pivotal-gpdb
    product_version: 6\.2\.1

- name: previous-5-release
  type: tanzunet
  source:
    api_token: ((public-tanzunet-refresh-token))
    endpoint: ((tanzunet-endpoint))
    product_slug: pivotal-gpdb
    product_version: 5\.25\.0

- name: gpdb6-centos6-test-packaging
  type: docker-image
  source:
    repository: pivotaldata/gpdb6-centos6-test-packaging
    tag: latest

- name: gpdb6-centos7-test-packaging
  type: docker-image
  source:
    repository: pivotaldata/gpdb6-centos7-test-packaging
    tag: latest

- name: gpdb6-ubuntu18.04-test-packaging
  type: docker-image
  source:
    repository: pivotaldata/gpdb6-ubuntu18.04-test-packaging
    tag: latest

## ======================================================================
##                   _
##   __ _ _ __   ___| |__   ___  _ __ ___
##  / _` | '_ \ / __| '_ \ / _ \| '__/ __|
## | (_| | | | | (__| | | | (_) | |  \__ \
##  \__,_|_| |_|\___|_| |_|\___/|_|  |___/
## ======================================================================
anchors:
- rpm-params: &rpm-params
    GPDB_LICENSE: Pivotal Software EULA
    GPDB_NAME: greenplum-db-6
    GPDB_OSS: false
    GPDB_RELEASE: 1
    GPDB_URL: https://network.pivotal.io/products/pivotal-gpdb/

## ======================================================================
##    _       _
##   (_) ___ | |__  ___
##   | |/ _ \| '_ \/ __|
##   | | (_) | |_) \__ \
##  _/ |\___/|_.__/|___/
## |__/
## ======================================================================
jobs:
- name: create_gpdb_rpm_installer_centos6
  plan:
  - in_parallel:
    - get: bin_gpdb_centos6
    - get: greenplum-database-release
      trigger: true
    - get: gpdb6-centos6-build
    - get: gpdb-osl
  - task: retrieve_gpdb_src
    file: greenplum-database-release/ci/((concourse-root))/tasks/retrieve_gpdb_src.yml
    image: gpdb6-centos6-build
    input_mapping:
      bin_gpdb: bin_gpdb_centos6
    vars:
      concourse-root: ((concourse-root))
  - task: build_rpm_gpdb_centos6
    file: greenplum-database-release/ci/concourse/tasks/build_gpdb_rpm.yml
    image: gpdb6-centos6-build
    input_mapping:
      bin_gpdb: bin_gpdb_centos6
      license_file: gpdb-osl
    params:
      <<: *rpm-params
      PLATFORM: rhel6
  - put: rpm_gpdb_centos6
    params:
      file: gpdb_rpm_installer/*.rpm

- name: create_gpdb_rpm_installer_centos7
  plan:
  - in_parallel:
    - get: bin_gpdb_centos7
    - get: greenplum-database-release
      trigger: true
    - get: gpdb6-centos7-build
    - get: gpdb-osl
  - task: retrieve_gpdb_src
    file: greenplum-database-release/ci/((concourse-root))/tasks/retrieve_gpdb_src.yml
    image: gpdb6-centos7-build
    input_mapping:
      bin_gpdb: bin_gpdb_centos7
    vars:
      concourse-root: ((concourse-root))
  - task: build_rpm_gpdb_centos7
    file: greenplum-database-release/ci/concourse/tasks/build_gpdb_rpm.yml
    image: gpdb6-centos7-build
    input_mapping:
      bin_gpdb: bin_gpdb_centos7
      license_file: gpdb-osl
    params:
      <<: *rpm-params
      PLATFORM: rhel7
  - put: rpm_gpdb_centos7
    params:
      file: gpdb_rpm_installer/*.rpm

- name: create_gpdb_deb_installer_ubuntu18.04
  plan:
  - in_parallel:
    - get: bin_gpdb_ubuntu18.04
    - get: greenplum-database-release
      trigger: true
    - get: gpdb6-ubuntu18.04-build
    - get: gpdb-osl
  - task: build_deb_gpdb_ubuntu18.04
    file: greenplum-database-release/ci/concourse/tasks/build_gpdb_deb.yml
    image: gpdb6-ubuntu18.04-build
    input_mapping:
      bin_gpdb: bin_gpdb_ubuntu18.04
      license_file: gpdb-osl
    params:
      GPDB_OSS: false
      PLATFORM: ubuntu18.04
  - put: deb_gpdb_ubuntu18.04
    params:
      file: gpdb_deb_installer/*.deb

- name: test_functionality_rpm_centos6
  plan:
  - in_parallel:
    - get: previous-6-release
      params:
        globs:
        - greenplum-db-*-rhel6-x86_64.rpm
    - get: previous-5-release
      params:
        globs:
        - greenplum-db-*-rhel6-x86_64.rpm
    - get: rpm_gpdb_centos6
      passed:
      - create_gpdb_rpm_installer_centos6
      trigger: true
    - get: greenplum-database-release
      passed:
      - create_gpdb_rpm_installer_centos6
    - get: gpdb6-centos6-test-packaging
  - task: test_rpm_functionality
    file: greenplum-database-release/ci/((concourse-root))/tasks/test_functionality_rpm.yml
    image: gpdb6-centos6-test-packaging
    input_mapping:
      gpdb_rpm_installer: rpm_gpdb_centos6
    params:
      PLATFORM: rhel6
    vars:
      concourse-root: ((concourse-root))

- name: test_functionality_rpm_centos7
  plan:
  - in_parallel:
    - get: previous-6-release
      params:
        globs:
        - greenplum-db-*-rhel7-x86_64.rpm
    - get: previous-5-release
      params:
        globs:
        - greenplum-db-*-rhel7-x86_64.rpm
    - get: rpm_gpdb_centos7
      passed:
      - create_gpdb_rpm_installer_centos7
      trigger: true
    - get: greenplum-database-release
      passed:
      - create_gpdb_rpm_installer_centos6
    - get: gpdb6-centos7-test-packaging
  - task: test_rpm_functionality
    file: greenplum-database-release/ci/((concourse-root))/tasks/test_functionality_rpm.yml
    image: gpdb6-centos7-test-packaging
    input_mapping:
      gpdb_rpm_installer: rpm_gpdb_centos7
    params:
      PLATFORM: rhel7
    vars:
      concourse-root: ((concourse-root))

- name: test_functionality_deb_ubuntu18.04
  plan:
  - in_parallel:
    - get: deb_gpdb_ubuntu18.04
      passed:
      - create_gpdb_deb_installer_ubuntu18.04
      trigger: true
    - get: greenplum-database-release
      passed:
      - create_gpdb_rpm_installer_centos6
    - get: gpdb6-ubuntu18.04-test-packaging
  - task: test_deb_functionality
    file: greenplum-database-release/ci/((concourse-root))/tasks/test_functionality_deb.yml
    image: gpdb6-ubuntu18.04-test-packaging
    input_mapping:
      gpdb_deb_installer: deb_gpdb_ubuntu18.04
    params:
      PLATFORM: ubuntu18.04
    vars:
      concourse-root: ((concourse-root))
