---
platform: linux

inputs:
- name: greenplum-database-release
- name: previous-6-release
- name: previous-5-release
- name: gpdb_rpm_installer


run:
  path: greenplum-database-release/ci/((concourse-root))/scripts/test_functionality_rpm.sh

params:
  PLATFORM:
