#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

apt-get update
apt-get -q=2 install ./libgpopt3/*.deb
apt-get -q=2 install ./libgpopt3-dev/*.deb

$DIR/../build-debian-package/run
