---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: bash
    tag: '5'

inputs:
- name: greenplum-database-release
- name: bin_gpdb_clients_windows

outputs:
- name: output_artifacts

run:
  path: bash
  args:
  - -ecx
  - |
    mv bin_gpdb_clients_windows/greenplum-db-clients-*.tar.gz bin_gpdb_clients_windows/bin_gpdb_clients.tar.gz
    greenplum-database-release/ci/concourse/scripts/build-gpdb-clients-msi.bash bin_gpdb_clients_windows/bin_gpdb_clients.tar.gz output_artifacts
