---
platform: linux

image_resource:
  type: registry-image

inputs:
- name: bin_gpdb_clients
- name: greenplum-database-release
- name: gpdb_src
  optional: true

outputs:
- name: gpdb_clients_deb_installer

run:
  path: greenplum-database-release/ci/concourse/scripts/build-gpdb-clients-deb.bash

params:
  PLATFORM:
  # Default values passed to deb package
  #  To override, please do so in pipeline
  GPDB_NAME: greenplum-db-clients
  GPDB_PREFIX: /usr/local
  RELEASE_VERSION:
  GPDB_MAJOR_VERSION:
