---
platform: linux

image_resource:
  type: registry-image

inputs:
- name: bin_gpdb
- name: greenplum-database-release
- name: gpdb_src
  optional: true

outputs:
- name: gpdb_rpm_installer

run:
  path: greenplum-database-release/ci/concourse/scripts/build-gpdb5-rpm.sh

params:
  PLATFORM:
  GPDB_VERSION:
  GPDB_RELEASE:
  GPDB_NAME:
  GPDB_LICENSE:
  GPDB_URL:
