---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotaldata/sles-gpdb-dev
    tag: 11-beta

inputs:
- name: bin_gpdb
- name: greenplum-database-release
- name: gpdb_src
  optional: true

outputs:
- name: gpdb_rpm_installer

run:
  path: greenplum-database-release/ci/concourse/scripts/build-gpdb5-rpm.sh

params:
  PLATFORM:
  # Default values passed to rpm SPEC
  #  To override, please do so in pipeline
  GPDB_NAME: greenplum-db-5
  GPDB_LICENSE: VMware Software EULA
  GPDB_URL: https://network.tanzu.vmware.com/products/pivotal-gpdb/
  GPDB_RELEASE: "1"
