---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: bash
    tag: latest

inputs:
- name: gpdb_src
- name: greenplum-database-release
- name: pivotal-gpdb

params:
  RUN_MODE:

run:
  path: bash
  args:
  - -ec
  - |
    # only check the versions on production environment
    # RUN_MODE: prod|dev
    if [ "${RUN_MODE}" != "prod" ]; then
      echo "CURRENT RUN_MODE: ${RUN_MODE}, NOT the 'prod' run mode and skip the check_version step"
      exit 0
    fi

    RELEASE_VERSION=$(cat pivotal-gpdb/version |cut -d "#" -f 1)
    gpdb_src_tag=$(cat gpdb_src/.git/ref)

    if [ "${gpdb_src_tag}" != "${RELEASE_VERSION}" ]; then
        cat <<EOF
    release version: "${RELEASE_VERSION}"
    gpdb_src_tag: "${gpdb_src_tag}"

    The tag for the gpdb_src does not match to the release version, therefore it is not a valid CI build job.
    EOF
        exit 1
    else
        cat <<EOF
    The tag for the gpdb_src matches to the release version!
    EOF
    fi
