---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: pivotaldata/ubuntu-gpdb-debian-dev
    tag: '16.04'
inputs:
- name: gpdb
- name: greenplum-database-release
outputs:
- name: debian_source_files

run:
  path: greenplum-database-release/ci/concourse/scripts/generate-ppa-debian-source-file.bash
