---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: golang
    tag: 1.16-buster

inputs:
- name: pivotal-gpdb
- name: greenplum-database-release
- name: tanzunet_client
- name: gpdb_rpm_installer_centos6
- name: gpdb_rpm_installer_centos7
- name: gpdb_deb_package
- name: gpdb-osl
- name: gpdb-odp

params:
  RUN_MODE:
  TANZUNET_ENDPOINT:
  TANZUNET_REFRESH_TOKEN:
  TANZUNET_PRODUCT_SLUG:
  TANZUNET_METADATA_FILE:
run:
  path: greenplum-database-release/ci/concourse/scripts/push-to-tanzunet.bash
