---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: golang
    tag: 1.14-buster

inputs:
- name: gpdb_src
- name: greenplum-database-release
- name: tanzunet_client
- name: gpdb_rpm_installer_centos6
- name: gpdb_rpm_installer_centos7
- name: gpdb_deb_package
params:
  TANZUNET_ENDPOINT:
  TANZUNET_REFRESH_TOKEN:
  TANZUNET_PRODUCT_SLUG:
  TANZUNET_S3_FILEPATH_PREFIX:
  TANZUNET_METADATA_FILE:
  PARENT_TANZUNET_SLUG:
run:
  path: greenplum-database-release/ci/concourse/scripts/push_to_tanzunet.bash
