#!/bin/bash

apt-get -q=2 update
apt-get -q=2 --no-install-recommends install -y equivs devscripts libwww-perl gnupg

pushd greenplum-database-release/packaging/${PKG_NAME} || exit
  origtargz
  DEBIAN_FRONTEND=noninteractive mk-build-deps --install --remove --tool "apt-get -q=2 --no-install-recommends"
  dpkg-buildpackage -us -uc
popd || exit


cp -a greenplum-database-release/packaging/*.deb debian-packages

ls -lh debian-packages/*.deb
for deb in debian-packages/*.deb; do
  dpkg-deb --info "$deb"
  dpkg-deb --contents "$deb"
done
