---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: bash
    tag: latest

inputs:
  - name: gpdb_src
  - name: greenplum-database-release_src

outputs:
  - name: release_artifacts

run:
  path: greenplum-database-release_src/concourse/scripts/gpdb_github_release.bash
