---
## ======================================================================
##                                           _
##  _ __ ___  ___  ___  _   _ _ __ ___ ___  | |_ _   _ _ __   ___  ___
## | '__/ _ \/ __|/ _ \| | | | '__/ __/ _ \ | __| | | | '_ \ / _ \/ __|
## | | |  __/\__ \ (_) | |_| | | | (_|  __/ | |_| |_| | |_) |  __/\__ \
## |_|  \___||___/\___/ \__,_|_|  \___\___|  \__|\__, | .__/ \___||___/
##                                               |___/|_|
## ======================================================================
resource_types:
- name: tanzunet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

## ======================================================================
##  _ __ ___  ___  ___  _   _ _ __ ___ ___  ___
## | '__/ _ \/ __|/ _ \| | | | '__/ __/ _ \/ __|
## | | |  __/\__ \ (_) | |_| | | | (_|  __/\__ \
## |_|  \___||___/\___/ \__,_|_|  \___\___||___/
## ======================================================================
resources:
- name: greenplum-database-release
  type: git
  source:
    branch: ((greenplum-database-release-git-branch))
    uri: ((greenplum-database-release-git-remote))

- name: centos-gpdb-dev-6
  type: docker-image
  source:
    repository: pivotaldata/centos-gpdb-dev
    tag: '6-gcc6.2-llvm3.7'

- name: centos-gpdb-dev-7
  type: docker-image
  source:
    repository: pivotaldata/centos-gpdb-dev
    tag: '7-gcc6.2-llvm3.7'

- name: bin_gpdb_centos6
  type: s3
  source:
    access_key_id: ((gpdb5-pipeline-s3-access-key-id))
    secret_access_key: ((gpdb5-pipeline-s3-secret-access-key))
    region_name: ((aws-region))
    bucket: ((gpdb-stable-builds-bucket-name))
    versioned_file: release_candidates/bin_gpdb_centos6/gpdb5/bin_gpdb.tar.gz

- name: rpm_gpdb_centos6
  type: s3
  source:
    access_key_id: ((gpdb5-pipeline-s3-access-key-id))
    secret_access_key: ((gpdb5-pipeline-s3-secret-access-key))
    region_name: ((aws-region))
    bucket: ((gpdb-stable-builds-bucket-name))
    versioned_file: release_candidates/rpm_gpdb_centos6/gpdb5/greenplum-db-5.99.0-rhel6-x86_64.rpm

- name: bin_gpdb_centos7
  type: s3
  source:
    access_key_id: ((gpdb5-pipeline-s3-access-key-id))
    secret_access_key: ((gpdb5-pipeline-s3-secret-access-key))
    region_name: ((aws-region))
    bucket: ((gpdb-stable-builds-bucket-name))
    versioned_file: release_candidates/bin_gpdb_centos7/gpdb5/bin_gpdb.tar.gz

- name: rpm_gpdb_centos7
  type: s3
  source:
    access_key_id: ((gpdb5-pipeline-s3-access-key-id))
    secret_access_key: ((gpdb5-pipeline-s3-secret-access-key))
    region_name: ((aws-region))
    bucket: ((gpdb-stable-builds-bucket-name))
    versioned_file: release_candidates/rpm_gpdb_centos7/gpdb5/greenplum-db-5.99.0-rhel7-x86_64.rpm

- name: bin_gpdb_sles11
  type: s3
  source:
    access_key_id: ((gpdb5-pipeline-s3-access-key-id))
    secret_access_key: ((gpdb5-pipeline-s3-secret-access-key))
    region_name: ((aws-region))
    bucket: ((gpdb-stable-builds-bucket-name))
    versioned_file: release_candidates/bin_gpdb_sles11/gpdb5/bin_gpdb.tar.gz

- name: rpm_gpdb_sles11
  type: s3
  source:
    access_key_id: ((gpdb5-pipeline-s3-access-key-id))
    secret_access_key: ((gpdb5-pipeline-s3-secret-access-key))
    region_name: ((aws-region))
    bucket: ((gpdb-stable-builds-bucket-name))
    versioned_file: release_candidates/rpm_gpdb_sles11/gpdb5/greenplum-db-5.99.0-sles11-x86_64.rpm

- name: previous-6-release
  type: tanzunet
  source:
    api_token: ((public-tanzunet-refresh-token))
    endpoint: ((tanzunet-endpoint))
    product_slug: pivotal-gpdb
    product_version: 6\.2\.1

- name: previous-5-release
  type: tanzunet
  source:
    api_token: ((public-tanzunet-refresh-token))
    endpoint: ((tanzunet-endpoint))
    product_slug: pivotal-gpdb
    product_version: 5\.25\.0

## ======================================================================
##                   _
##   __ _ _ __   ___| |__   ___  _ __ ___
##  / _` | '_ \ / __| '_ \ / _ \| '__/ __|
## | (_| | | | | (__| | | | (_) | |  \__ \
##  \__,_|_| |_|\___|_| |_|\___/|_|  |___/
## ======================================================================
anchors:
- rpm-params: &rpm-params
    GPDB_NAME: greenplum-db-5
    GPDB_LICENSE: VMware Software EULA
    GPDB_URL: https://network.pivotal.io/products/pivotal-gpdb/
    GPDB_RELEASE: 1
    GPDB_VERSION: "5.99.0"

## ======================================================================
##    _       _
##   (_) ___ | |__  ___
##   | |/ _ \| '_ \/ __|
##   | | (_) | |_) \__ \
##  _/ |\___/|_.__/|___/
## |__/
## ======================================================================
jobs:
- name: create_gpdb_rpm_installer_centos6
  plan:
  - in_parallel:
    - get: bin_gpdb
      resource: bin_gpdb_centos6
    - get: centos-gpdb-dev-6
    - get: greenplum-database-release
      trigger: true
  - task: build_rpm_gpdb_centos6
    file: greenplum-database-release/ci/concourse/tasks/build-gpdb5-rpm.yml
    image: centos-gpdb-dev-6
    params:
      <<: *rpm-params
      PLATFORM: "rhel6"
  - put: rpm_gpdb_centos6
    params:
      file: gpdb_rpm_installer/*.rpm

- name: create_gpdb_rpm_installer_centos7
  plan:
  - in_parallel:
    - get: bin_gpdb
      resource: bin_gpdb_centos7
    - get: centos-gpdb-dev-7
    - get: greenplum-database-release
      trigger: true
  - task: build_rpm_gpdb_centos7
    file: greenplum-database-release/ci/concourse/tasks/build-gpdb5-rpm.yml
    image: centos-gpdb-dev-7
    params:
      <<: *rpm-params
      PLATFORM: "rhel7"
  - put: rpm_gpdb_centos7
    params:
      file: gpdb_rpm_installer/*.rpm

- name: create_gpdb_rpm_installer_sles11
  plan:
  - in_parallel:
    - get: bin_gpdb
      resource: bin_gpdb_sles11
    - get: greenplum-database-release
      trigger: true
  - task: build_rpm_gpdb_sles11
    file: greenplum-database-release/ci/concourse/tasks/build-gpdb5-rpm-sles.yml
    params:
      <<: *rpm-params
      PLATFORM: "sles11"
  - put: rpm_gpdb_sles11
    params:
      file: gpdb_rpm_installer/*.rpm

- name: test_functionality_rpm_centos6
  plan:
  - in_parallel:
    - get: greenplum-database-release
      passed: [create_gpdb_rpm_installer_centos6]
    - get: rpm_gpdb_centos6
      passed: [create_gpdb_rpm_installer_centos6]
      trigger: true
    - get: previous-6-release
      params:
        globs: [greenplum-db-*-rhel6-x86_64.rpm]
    - get: previous-5-release
      params:
        globs: [greenplum-db-*-rhel6-x86_64.rpm]
    - get: centos-gpdb-dev-6
  - task: test_rpm_functionality
    image: centos-gpdb-dev-6
    file: greenplum-database-release/ci/concourse/tasks/test-functionality-rpm.yml
    input_mapping:
      gpdb_rpm_installer: rpm_gpdb_centos6
    params:
      PLATFORM: "rhel6"

- name: test_functionality_rpm_centos7
  plan:
  - in_parallel:
    - get: greenplum-database-release
      passed: [create_gpdb_rpm_installer_centos7]
    - get: rpm_gpdb_centos7
      passed: [create_gpdb_rpm_installer_centos7]
      trigger: true
    - get: previous-6-release
      params:
        globs: [greenplum-db-*-rhel7-x86_64.rpm]
    - get: previous-5-release
      params:
        globs: [greenplum-db-*-rhel7-x86_64.rpm]
    - get: centos-gpdb-dev-7
  - task: test_rpm_functionality
    image: centos-gpdb-dev-7
    file: greenplum-database-release/ci/concourse/tasks/test-functionality-rpm.yml
    input_mapping:
      gpdb_rpm_installer: rpm_gpdb_centos7
    params:
      PLATFORM: "rhel7"

- name: test_functionality_rpm_sles11
  plan:
  - in_parallel:
    - get: greenplum-database-release
      passed: [create_gpdb_rpm_installer_sles11]
    - get: rpm_gpdb_sles11
      passed: [create_gpdb_rpm_installer_sles11]
      trigger: true
    - get: previous-5-release
      params:
        globs: [greenplum-db-*-sles11-x86_64.rpm]
  - task: test_rpm_functionality
    file: greenplum-database-release/ci/concourse/tasks/test-functionality-rpm-sles.yml
    input_mapping:
      gpdb_rpm_installer: rpm_gpdb_sles11
    params:
      PLATFORM: "sles11"
