# Copyright (C) 2019-Present VMware, and affiliates Inc. All rights reserved.
# This program and the accompanying materials are made available under the
# terms of the under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain a
# copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations under
# the License.
---
resource_types:
- name: gcs
  type: docker-image
  source:
    repository: frodenas/gcs-resource

- name: ppa
  type: docker-image
  source:
    repository: seveas/concourse-ppa-resource

- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: slack-alert
  type: slack-notification
  icon: slack
  source:
    url: ((releng-webhook-url))

## Image Resources
- name: gpdb6-centos6-build
  type: docker-image
  icon: docker
  source:
    repository: pivotaldata/gpdb6-centos6-build
    tag: 'latest'

- name: gpdb6-centos7-build
  type: docker-image
  icon: docker
  source:
    repository: pivotaldata/gpdb6-centos7-build
    tag: 'latest'

- name: gpdb6-photon3-build
  type: docker-image
  icon: docker
  source:
    repository: pivotaldata/gpdb6-photon3-build
    tag: 'latest'
    username: ((docker_username))
    password: ((docker_password))

- name: gpdb6-ubuntu18.04-build
  type: docker-image
  icon: docker
  source:
    repository: pivotaldata/gpdb6-ubuntu18.04-build
    tag: 'latest'

- name: gpdb_src
  type: git
  icon: git
  source:
    branch: ((gpdb-git-branch))
    uri: ((gpdb-git-remote))
    tag_filter: ((gpdb-git-tag-filter))

- name: greenplum-database-release
  type: git
  icon: git
  source:
    branch: ((greenplum-database-release-git-branch))
    uri: ((greenplum-database-release-git-remote))

- name: gpdb_release
  type: github-release
  icon: github-circle
  source:
    owner: ((gpdb-release-owner))
    repository: ((gpdb-release-repository))
    access_token: ((gpdb-release-access-token))

- name: license_file
  type: gcs
  icon: google
  source:
    bucket: ((gcs-bucket-for-oss))
    json_key: ((concourse-gcs-resources-service-account-key))
    regexp: osl/released/gpdb6/open_source_license_greenplum-database-6.0.0-97773a0-(.*).txt

- name: tanzunet_client
  type: github-release
  source:
    owner: pivotal
    repository: gp-tanzunet-client
    access_token: ((github-token-gp-releng))
    tag_filter: ((tanzunet-client-version))

## gp internal artifacts
- name: python-centos6
  type: gcs
  icon: google
  source:
    json_key: ((concourse-gcs-resources-service-account-key))
    bucket: pivotal-gpdb-concourse-resources-prod
    regexp: gp-internal-artifacts/centos6/python-(2\.7\.12-.*).tar.gz

- name: python-centos7
  type: gcs
  icon: google
  source:
    json_key: ((concourse-gcs-resources-service-account-key))
    bucket: pivotal-gpdb-concourse-resources-prod
    regexp: gp-internal-artifacts/centos7/python-(2\.7\.12-.*).tar.gz

- name: python-photon3
  type: gcs
  icon: google
  source:
    json_key: ((concourse-gcs-resources-service-account-key))
    bucket: pivotal-gpdb-concourse-resources-prod
    regexp: gp-internal-artifacts/photon3/python-(2\.7\.12.*).tar.gz

- name: python-ubuntu18.04
  type: gcs
  icon: google
  source:
    json_key: ((concourse-gcs-resources-service-account-key))
    bucket: pivotal-gpdb-concourse-resources-prod
    regexp: gp-internal-artifacts/ubuntu18.04/python-(2\.7\.12-.*).tar.gz

## RHEL6 Resources
- name: bin_gpdb_centos6
  type: gcs
  icon: google
  source:
    json_key: ((concourse-gcs-resources-service-account-key))
    bucket: ((gcs-bucket-intermediates-for-oss))
    versioned_file: ((pipeline-name))/bin_gpdb_centos6/bin_gpdb.tar.gz

- name: bin_gpdb_centos6_release
  type: gcs
  icon: google
  source:
    bucket: ((gcs-bucket-for-oss))
    json_key: ((concourse-gcs-resources-service-account-key))
    regexp: greenplum-oss-server/released/gpdb6/server-(.*)-rhel6_x86_64.tar.gz

- name: gpdb_rpm_installer_centos6
  type: gcs
  icon: google
  source:
    bucket: ((gcs-bucket-for-oss))
    json_key: ((concourse-gcs-resources-service-account-key))
    regexp: greenplum-oss-server/released/gpdb6/greenplum-db-(.*)-rhel6-x86_64.rpm

## RHEL7 Resources
- name: bin_gpdb_centos7
  type: gcs
  icon: google
  source:
    json_key: ((concourse-gcs-resources-service-account-key))
    bucket: ((gcs-bucket-intermediates-for-oss))
    versioned_file: ((pipeline-name))/bin_gpdb_centos7/bin_gpdb.tar.gz

- name: bin_gpdb_centos7_release
  type: gcs
  icon: google
  source:
    bucket: ((gcs-bucket-for-oss))
    json_key: ((concourse-gcs-resources-service-account-key))
    regexp: greenplum-oss-server/released/gpdb6/server-(.*)-rhel7_x86_64.tar.gz

- name: gpdb_rpm_installer_centos7
  type: gcs
  icon: google
  source:
    bucket: ((gcs-bucket-for-oss))
    json_key: ((concourse-gcs-resources-service-account-key))
    regexp: greenplum-oss-server/released/gpdb6/greenplum-db-(.*)-rhel7-x86_64.rpm


## Photon3 Resources
- name: bin_gpdb_photon3
  type: gcs
  icon: google
  source:
    json_key: ((concourse-gcs-resources-service-account-key))
    bucket: ((gcs-bucket-intermediates-for-oss))
    versioned_file: ((pipeline-name))/bin_gpdb_photon3/bin_gpdb.tar.gz

- name: bin_gpdb_photon3_release
  type: gcs
  icon: google
  source:
    bucket: ((gcs-bucket-for-oss))
    json_key: ((concourse-gcs-resources-service-account-key))
    regexp: greenplum-oss-server/released/gpdb6/server-(.*)-photon3_x86_64.tar.gz

- name: gpdb_rpm_installer_photon3
  type: gcs
  icon: google
  source:
    bucket: ((gcs-bucket-for-oss))
    json_key: ((concourse-gcs-resources-service-account-key))
    regexp: greenplum-oss-server/released/gpdb6/greenplum-db-(.*)-photon3-x86_64.rpm

## Ubuntu18.04 Resources
- name: bin_gpdb_ubuntu18.04_for_github
  type: gcs
  icon: google
  source:
    json_key: ((concourse-gcs-resources-service-account-key))
    bucket: ((gcs-bucket-intermediates-for-oss))
    versioned_file: ((pipeline-name))/bin_gpdb_ubuntu18.04_github/bin_gpdb.tar.gz

- name: bin_gpdb_ubuntu18.04_for_ppa
  type: gcs
  icon: google
  source:
    json_key: ((concourse-gcs-resources-service-account-key))
    bucket: ((gcs-bucket-intermediates-for-oss))
    versioned_file: ((pipeline-name))/bin_gpdb_ubuntu18.04_ppa/bin_gpdb.tar.gz

- name: bin_gpdb_ubuntu18.04_release
  type: gcs
  icon: google
  source:
    bucket: ((gcs-bucket-for-oss))
    json_key: ((concourse-gcs-resources-service-account-key))
    regexp: greenplum-oss-server/released/gpdb6/server-(.*)-ubuntu18.04_x86_64.tar.gz

- name: gpdb_deb_package
  type: gcs
  icon: google
  source:
    bucket: ((gcs-bucket-for-oss))
    json_key: ((concourse-gcs-resources-service-account-key))
    regexp: greenplum-oss-server/released/gpdb6/greenplum-db-(.*)-ubuntu18.04-amd64.deb

- name: ppa_release_version
  type: gcs
  icon: google
  source:
    json_key: ((concourse-gcs-resources-service-account-key))
    bucket: ((gcs-bucket-intermediates-for-oss))
    versioned_file: ((pipeline-name))/ppa_release_version/version.txt

- name: greenplum_db_ppa
  type: ppa
  source:
    ppa: ((ppa-login))
    package: ((ppa-package-name))
    api_token: ((ppa-api-token))
jobs:
- name: compile_gpdb_centos6
  on_failure: &slack-alert
    put: slack-alert
    params:
      # yamllint disable-line rule:line-length
      text: Hey team, <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|greenplum-database-release/$BUILD_JOB_NAME> failed.
  plan:
  - in_parallel:
    - get: gpdb_src
      trigger: true
    - get: greenplum-database-release
    - get: gpdb6-centos6-build
    - get: python-tarball
      resource: python-centos6
  - task: compile_gpdb
    file: greenplum-database-release/ci/concourse/tasks/compile-gpdb-oss.yml
    image: gpdb6-centos6-build
    params:
      PREFIX: /usr/local
  - put: bin_gpdb_centos6
    params:
      file: gpdb_artifacts/bin_gpdb.tar.gz

- name: compile_gpdb_centos7
  on_failure:
    <<: *slack-alert
  plan:
  - in_parallel:
    - get: gpdb_src
      trigger: true
    - get: greenplum-database-release
    - get: gpdb6-centos7-build
    - get: python-tarball
      resource: python-centos7
  - task: compile_gpdb
    image: gpdb6-centos7-build
    file: greenplum-database-release/ci/concourse/tasks/compile-gpdb-oss.yml
    params:
      PREFIX: /usr/local
  - put: bin_gpdb_centos7
    params:
      file: gpdb_artifacts/bin_gpdb.tar.gz

- name: compile_gpdb_photon3
  on_failure:
    <<: *slack-alert
  plan:
  - in_parallel:
    - get: gpdb_src
      trigger: true
    - get: greenplum-database-release
    - get: gpdb6-photon3-build
    - get: python-tarball
      resource: python-photon3
  - task: compile_gpdb
    image: gpdb6-photon3-build
    file: greenplum-database-release/ci/concourse/tasks/compile-gpdb-oss.yml
    params:
      PREFIX: /usr/local
  - put: bin_gpdb_photon3
    params:
      file: gpdb_artifacts/bin_gpdb.tar.gz

- name: compile_gpdb_ubuntu18.04_for_github
  on_failure:
    <<: *slack-alert
  plan:
  - in_parallel:
    - get: gpdb_src
      trigger: true
    - get: greenplum-database-release
    - get: gpdb6-ubuntu18.04-build
    - get: python-tarball
      resource: python-ubuntu18.04
  - task: compile_gpdb
    image: gpdb6-ubuntu18.04-build
    file: greenplum-database-release/ci/concourse/tasks/compile-gpdb-oss.yml
    params:
      PREFIX: /usr/local
  - put: bin_gpdb_ubuntu18.04_for_github
    params:
      file: gpdb_artifacts/bin_gpdb.tar.gz

- name: compile_gpdb_ubuntu18.04_for_ppa
  on_failure:
    <<: *slack-alert
  plan:
  - in_parallel:
    - get: gpdb_src
      trigger: true
    - get: greenplum-database-release
    - get: gpdb6-ubuntu18.04-build
    - get: python-tarball
      resource: python-ubuntu18.04
  - task: compile_gpdb
    image: gpdb6-ubuntu18.04-build
    file: greenplum-database-release/ci/concourse/tasks/compile-gpdb-oss.yml
    params:
      PREFIX: /opt
  - put: bin_gpdb_ubuntu18.04_for_ppa
    params:
      file: gpdb_artifacts/bin_gpdb.tar.gz

- name: rhel6 packaging
  on_failure:
    <<: *slack-alert
  plan:
  - in_parallel:
    - get: gpdb_src
      trigger: true
      passed: [compile_gpdb_centos6]
    - get: greenplum-database-release
      passed: [compile_gpdb_centos6]
    - get: bin_gpdb_centos6
      passed: [compile_gpdb_centos6]
    - get: gpdb6-centos6-build
    - get: license_file
  - task: create_gpdb_rpm_package
    file: greenplum-database-release/ci/concourse/tasks/build-gpdb-rpm.yml
    image: gpdb6-centos6-build
    input_mapping:
      bin_gpdb: bin_gpdb_centos6
    params:
      PLATFORM: "rhel6"
      GPDB_NAME: greenplum-db-6
      GPDB_RELEASE: 1
      GPDB_LICENSE: VMware Software EULA
      GPDB_URL: https://github.com/greenplum-db/gpdb
      GPDB_OSS: true
  - put: gpdb_rpm_installer_centos6
    params:
      file: gpdb_rpm_installer/*.rpm

- name: rhel7 packaging
  on_failure:
    <<: *slack-alert
  plan:
  - in_parallel:
    - get: gpdb_src
      trigger: true
      passed: [compile_gpdb_centos7]
    - get: greenplum-database-release
      passed: [compile_gpdb_centos7]
    - get: bin_gpdb_centos7
      passed: [compile_gpdb_centos7]
    - get: gpdb6-centos7-build
    - get: license_file
  - task: create_gpdb_rpm_package
    file: greenplum-database-release/ci/concourse/tasks/build-gpdb-rpm.yml
    image: gpdb6-centos7-build
    input_mapping:
      bin_gpdb: bin_gpdb_centos7
    params:
      PLATFORM: "rhel7"
      GPDB_NAME: greenplum-db-6
      GPDB_RELEASE: 1
      GPDB_LICENSE: VMware Software EULA
      GPDB_URL: https://github.com/greenplum-db/gpdb
      GPDB_OSS: true
  - put: gpdb_rpm_installer_centos7
    params:
      file: gpdb_rpm_installer/*.rpm


- name: photon3 packaging
  on_failure:
    <<: *slack-alert
  plan:
  - in_parallel:
    - get: gpdb_src
      trigger: true
      passed: [compile_gpdb_photon3]
    - get: greenplum-database-release
    - get: bin_gpdb_photon3
      passed: [compile_gpdb_photon3]
    - get: gpdb6-photon3-build
    - get: license_file
  - task: create_gpdb_rpm_package
    file: greenplum-database-release/ci/concourse/tasks/build-gpdb-rpm.yml
    image: gpdb6-photon3-build
    input_mapping:
      bin_gpdb: bin_gpdb_photon3
    params:
      PLATFORM: "photon3"
      GPDB_NAME: greenplum-db-6
      GPDB_RELEASE: 1
      GPDB_LICENSE: VMware Software EULA
      GPDB_URL: https://github.com/greenplum-db/gpdb
      GPDB_OSS: false
  - put: gpdb_rpm_installer_photon3
    params:
      file: gpdb_rpm_installer/*.rpm

- name: ubuntu18.04 packaging
  on_failure:
    <<: *slack-alert
  plan:
  - in_parallel:
    - get: gpdb_src
      trigger: true
      passed: [compile_gpdb_ubuntu18.04_for_github]
    - get: greenplum-database-release
      passed: [compile_gpdb_ubuntu18.04_for_github]
    - get: bin_gpdb_ubuntu18.04_for_github
      passed: [compile_gpdb_ubuntu18.04_for_github]
    - get: gpdb6-ubuntu18.04-build
    - get: license_file
  - task: create_gpdb_deb_package
    file: greenplum-database-release/ci/concourse/tasks/build-gpdb-deb.yml
    image: gpdb6-ubuntu18.04-build
    input_mapping:
      bin_gpdb: bin_gpdb_ubuntu18.04_for_github
    params:
      PLATFORM: "ubuntu18.04"
      GPDB_OSS: true
  - put: gpdb_deb_package
    params:
      file: gpdb_deb_installer/*.deb

- name: publish to ppa
  on_failure:
    <<: *slack-alert
  plan:
  - in_parallel:
    - get: gpdb_src
      passed: [compile_gpdb_ubuntu18.04_for_ppa]
    - get: greenplum-database-release
      passed: [compile_gpdb_ubuntu18.04_for_ppa]
    - get: bin_gpdb_ubuntu18.04_for_ppa
      passed: [compile_gpdb_ubuntu18.04_for_ppa]
      trigger: true
    - get: license_file
  - task: push to ppa
    file: greenplum-database-release/ci/concourse/tasks/publish-to-ppa.yml
    input_mapping:
      bin_gpdb_ubuntu18.04: bin_gpdb_ubuntu18.04_for_ppa
    params:
      PPA_REPO: ((ppa-repository))
      GPG_PRIVATE_KEY: ((gpg-private-key))
      RELEASE_MESSAGE: ((release-message))
      DEBFULLNAME: ((debian-package-maintainer-fullname))
      DEBEMAIL: ((debian-package-maintainer-email))
  - put: ppa_release_version
    params:
      file: ppa_release/version.txt

- name: verify ppa release
  on_failure:
    <<: *slack-alert
  plan:
  - in_parallel:
    - get: greenplum-database-release
      passed: [publish to ppa]
    - get: greenplum_db_ppa
      trigger: true
    - get: ppa_release_version
      passed: [publish to ppa]
  - task: verify ppa release status
    file: greenplum-database-release/ci/concourse/tasks/verify-ppa-release.yml

- name: release
  on_failure:
    <<: *slack-alert
  plan:
  - in_parallel:
    - get: greenplum-database-release
      passed:
      - rhel6 packaging
      - rhel7 packaging
      - photon3 packaging
      - ubuntu18.04 packaging
      - verify ppa release
    - get: gpdb_src
      passed:
      - rhel6 packaging
      - rhel7 packaging
      - photon3 packaging
      - ubuntu18.04 packaging
    - get: bin_gpdb_centos6
      passed: [rhel6 packaging]
      trigger: true
    - get: bin_gpdb_centos7
      passed: [rhel7 packaging]
      trigger: true
    - get: bin_gpdb_photon3
      passed: [photon3 packaging]
      trigger: true
    - get: bin_gpdb_ubuntu18.04_for_github
      passed: [ubuntu18.04 packaging]
      trigger: true
    - get: gpdb_rpm_installer_centos6
      passed: [rhel6 packaging]
    - get: gpdb_rpm_installer_centos7
      passed: [rhel7 packaging]
    - get: gpdb_rpm_installer_photon3
      passed: [photon3 packaging]
    - get: gpdb_deb_package
      passed: [ubuntu18.04 packaging]
    - get: gpdb6-centos6-build
    - get: license_file
      passed:
      - rhel6 packaging
      - rhel7 packaging
      - photon3 packaging
      - ubuntu18.04 packaging
  - task: rename_gpdb_tarball
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: pivotaldata/gpdb6-centos6-build
      inputs:
      - name: gpdb_src
      - name: bin_gpdb_centos6
      - name: bin_gpdb_centos7
      - name: bin_gpdb_photon3
      - name: bin_gpdb_ubuntu18.04_for_github
      outputs:
      - name: releases
      run:
        path: bash
        args:
        - -ec
        - |
          gpdb_semver=$(gpdb_src/getversion | cut -d' ' -f1)
          cp -v bin_gpdb_centos6/bin_gpdb.tar.gz releases/server-${gpdb_semver}-rhel6_x86_64.tar.gz
          cp -v bin_gpdb_centos7/bin_gpdb.tar.gz releases/server-${gpdb_semver}-rhel7_x86_64.tar.gz
          cp -v bin_gpdb_photon3/bin_gpdb.tar.gz releases/server-${gpdb_semver}-photon3_x86_64.tar.gz
          cp -v bin_gpdb_ubuntu18.04_for_github/bin_gpdb.tar.gz releases/server-${gpdb_semver}-ubuntu18.04_x86_64.tar.gz
  - task: verify_gpdb_versions
    file: gpdb_src/concourse/tasks/verify_gpdb_versions.yml
    input_mapping:
      bin_gpdb_ubuntu18.04: bin_gpdb_ubuntu18.04_for_github
  - in_parallel:
    - put: bin_gpdb_centos6_release
      params:
        file: "releases/server-*rhel6*.tar.gz"
    - put: bin_gpdb_centos7_release
      params:
        file: "releases/server-*rhel7*.tar.gz"
    - put: bin_gpdb_photon3_release
      params:
        file: "releases/server-*photon3*.tar.gz"
    - put: bin_gpdb_ubuntu18.04_release
      params:
        file: "releases/server-*ubuntu18.04*.tar.gz"

- name: publish_gpdb_github_release
  on_failure:
    <<: *slack-alert
  plan:
  - in_parallel:
    - get: gpdb_src
      passed: [release]
    - get: license_file
      passed: [release]
    - get: gpdb_rpm_installer_centos6
      passed: [release]
      trigger: true
    - get: gpdb_rpm_installer_centos7
      passed: [release]
      trigger: true
    - get: gpdb_deb_package
      passed: [release]
      trigger: true
    - get: greenplum-database-release
      passed: [release]
  - task: gpdb_github_release
    file: greenplum-database-release/ci/concourse/tasks/gpdb-github-release.yml
  - put: gpdb_release
    params:
      name: release_artifacts/name
      tag: release_artifacts/tag
      body: release_artifacts/body
      commitish: release_artifacts/commitish
      globs:
      - release_artifacts/*.tar.gz
      - release_artifacts/*.zip
      - license_file/*.txt
      - gpdb_rpm_installer_centos6/*.rpm
      - gpdb_rpm_installer_centos7/*.rpm
      - gpdb_deb_package/*.deb

- name: push_to_tanzunet
  plan:
  - in_parallel:
    - get: gpdb_src
      passed: [release]
    - get: tanzunet_client
    - get: license_file
      passed: [release]
    - get: gpdb_rpm_installer_centos6
      passed: [release]
      trigger: true
    - get: gpdb_rpm_installer_centos7
      passed: [release]
      trigger: true
    - get: gpdb_deb_package
      passed: [release]
      trigger: true
    - get: greenplum-database-release
      passed: [release]
      trigger: true
  - task: push_to_tanzunet
    file: greenplum-database-release/ci/concourse/tasks/push-to-tanzunet.yml
    params:
      TANZUNET_ENDPOINT: ((tanzunet-endpoint))
      TANZUNET_METADATA_FILE: ((tanzunet-metadata-file-path))
      TANZUNET_REFRESH_TOKEN: ((tanzunet-refresh-token))
      TANZUNET_PRODUCT_SLUG: ((tanzunet-product-slug))
