---
name: code-style-check

# yamllint disable-line rule:truthy
on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: run make lint
      run: |
        make lint
