---
name: code-style-check

# yamllint disable-line rule:truthy
on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: docker://github/super-linter:v3.13.1
      env:
        VALIDATE_MD: true
        VALIDATE_BASH: true
        VALIDATE_YAML: true
    - name: check shfmt
      run: make shfmt
